### ISSUE TITLE
docs: initial example not immediately runnable (?)

### ISSUE THREAD

**Issue by gvwilson** [Fault-lang/Fault#26]
- Copy the sandwich model from the home page http://fault.tech/ to `sandwich.fsystem`.
- Install Fault using `make fault-z3`.
- Run `fault -f=sandwich.fsystem`.
- Get Go error shown below.

```
panic:  [recovered]
	panic: Invalid spec syntax spec on line 1 col 0 in spec sandwich.fsystem [recovered]
	panic: Invalid spec syntax spec on line 1 col 0 in spec sandwich.fsystem
```

- Change first line of example file from `spec sandwich` to `system sandwich`.
- Example runs as expected.

I expected the first example to run as-is with a minimal set of command-line options.

**Comment by mbellotti** [comment]
Oh this is great. Exactly the sort of stuff I was hoping for!

Here's the problem. The sandwich example is a spec. Spec files need to have the extension `.fspec` It gives you that error because you named it `.fsystem` but then declared it a spec file. 

I'm actually surprised it got as far into the parser as it did. I would have expected Antlr to pick it up much earlier with a prettier and cleaner error message. So I added some validation language to check that the declaration matches the file type and deliver a friendlier error message.

When you change the declaration to system it loads the grammar for system files but doesn't find anything to parse as there is no state chart. As a result it sends a mostly empty and meaningless AST through. It appears to work, but there's no model to run so it just fails silently. Added some validation to check for these scenarios as well.

While doing this I found ANOTHER edge case myself around running individual spec files that do not have run blocks (because they were designed to be imported). Added some additional checks to short-circuit the compiling and allow the compiler to exit successfully but with the explanation that there is actually no model to run.

Thanks so much for reporting this... please accept this facepalming kitten as a token of gratitude 😀 

![](https://media.giphy.com/media/yFQ0ywscgobJK/giphy.gif)
